import { Peer, ServerConfigState } from '../types';

// RFC 7748 X25519 Curve25519 Scalar Multiplication
function x25519(privateKeyBytes: Uint8Array): Uint8Array {
  const k = new Uint8Array(32);
  k.set(privateKeyBytes);
  k[0] &= 248;
  k[31] &= 127;
  k[31] |= 64;

  const p = (1n << 255n) - 19n;
  const pack = (x: bigint): Uint8Array => {
    const b = new Uint8Array(32);
    for (let i = 0; i < 32; i++) {
      b[i] = Number((x >> BigInt(i * 8)) & 0xffn);
    }
    return b;
  };

  const add = (a: bigint, b: bigint) => (a + b) % p;
  const sub = (a: bigint, b: bigint) => (a - b + p) % p;
  const mul = (a: bigint, b: bigint) => (a * b) % p;
  const inv = (a: bigint) => {
    let res = 1n;
    let base = a;
    let exp = p - 2n;
    while (exp > 0n) {
      if (exp & 1n) res = mul(res, base);
      base = mul(base, base);
      exp >>= 1n;
    }
    return res;
  };

  let x1 = 9n, x2 = 1n, z2 = 0n, x3 = 9n, z3 = 1n;
  for (let i = 254; i >= 0; i--) {
    const bit = BigInt((k[Math.floor(i / 8)] >> (i % 8)) & 1);
    if (bit) {
      [x2, x3] = [x3, x2];
      [z2, z3] = [z3, z2];
    }
    const a = add(x2, z2);
    const b = sub(x2, z2);
    const c = add(x3, z3);
    const d = sub(x3, z3);
    const da = mul(d, a);
    const cb = mul(c, b);
    x3 = mul(add(da, cb), add(da, cb));
    z3 = mul(x1, mul(sub(da, cb), sub(da, cb)));
    const aa = mul(a, a);
    const bb = mul(b, b);
    const e = sub(aa, bb);
    x2 = mul(aa, bb);
    z2 = mul(e, add(aa, mul(121665n, e)));
    if (bit) {
      [x2, x3] = [x3, x2];
      [z2, z3] = [z3, z2];
    }
  }
  return pack(mul(x2, inv(z2)));
}

/**
 * Derives the exact Curve25519 public key from a base64 encoded WireGuard private key
 */
export function getPublicKey(privateKeyBase64: string): string {
  try {
    const binary = atob(privateKeyBase64);
    const bytes = new Uint8Array(binary.length);
    for (let i = 0; i < binary.length; i++) {
      bytes[i] = binary.charCodeAt(i);
    }
    const pubBytes = x25519(bytes);
    let binaryPub = '';
    for (let i = 0; i < pubBytes.length; i++) {
      binaryPub += String.fromCharCode(pubBytes[i]);
    }
    return btoa(binaryPub);
  } catch (e) {
    console.error('Failed to derive public key:', e);
    return '';
  }
}

/**
 * Generates a valid Curve25519 WireGuard keypair
 */
export function generateKeyPair(): { privateKey: string; publicKey: string } {
  const privBytes = new Uint8Array(32);
  window.crypto.getRandomValues(privBytes);
  privBytes[0] &= 248;
  privBytes[31] &= 127;
  privBytes[31] |= 64;

  let binaryPriv = '';
  for (let i = 0; i < privBytes.length; i++) {
    binaryPriv += String.fromCharCode(privBytes[i]);
  }
  const privateKey = btoa(binaryPriv);
  const publicKey = getPublicKey(privateKey);

  return { privateKey, publicKey };
}

/**
 * Formats full WireGuard wg0.conf server configuration
 */
export function generateServerConfigText(config: ServerConfigState, peers: Peer[]): string {
  let conf = `# ==========================================\n`;
  conf += `# WireGuard Server Configuration\n`;
  conf += `# Interface: ${config.interfaceName}\n`;
  conf += `# Generated by WireGuard Server Management Studio\n`;
  conf += `# ==========================================\n\n`;

  conf += `[Interface]\n`;
  conf += `Address = ${config.serverIP}\n`;
  conf += `ListenPort = ${config.listenPort}\n`;
  conf += `PrivateKey = ${config.privateKey}\n`;
  if (config.mtu) conf += `MTU = ${config.mtu}\n`;
  if (config.postUp) conf += `PostUp = ${config.postUp}\n`;
  if (config.postDown) conf += `PostDown = ${config.postDown}\n`;
  conf += `\n`;

  peers.forEach((peer) => {
    conf += `# Peer: ${peer.name}\n`;
    conf += `[Peer]\n`;
    conf += `PublicKey = ${peer.publicKey}\n`;
    conf += `AllowedIPs = ${peer.allocatedIP}/32\n\n`;
  });

  return conf;
}

/**
 * Formats individual client .conf file for import into WireGuard Client App
 */
export function generateClientConfigText(
  peer: Peer,
  serverConfig: ServerConfigState,
  serverEndpointHost?: string
): string {
  let endpoint = serverEndpointHost || serverConfig.endpointHost;
  if (!endpoint || endpoint === 'YOUR_SERVER_PUBLIC_IP') {
    endpoint = 'vpn.physikcraft.de';
  }
  let conf = `[Interface]\n`;
  conf += `PrivateKey = ${peer.privateKey}\n`;
  conf += `Address = ${peer.allocatedIP}/32\n`;
  if (serverConfig.dns) conf += `DNS = ${serverConfig.dns}\n`;
  if (serverConfig.mtu) conf += `MTU = ${serverConfig.mtu}\n`;
  conf += `\n[Peer]\n`;
  conf += `PublicKey = ${serverConfig.publicKey}\n`;
  conf += `Endpoint = ${endpoint}:${serverConfig.listenPort}\n`;
  conf += `AllowedIPs = 0.0.0.0/0, ::/0\n`;
  if (serverConfig.persistentKeepalive > 0) {
    conf += `PersistentKeepalive = ${serverConfig.persistentKeepalive}\n`;
  }

  return conf;
}

/**
 * Auto-calculates next available client IP inside subnet e.g. 10.8.0.x
 */
export function getNextAvailableIP(subnet: string, existingPeers: Peer[]): string {
  const match = subnet.match(/^(\d+\.\d+\.\d+)\.\d+\/(\d+)$/);
  if (!match) return '10.8.0.2';

  const basePrefix = match[1];
  const usedLastOctets = new Set(
    existingPeers.map((p) => {
      const parts = p.allocatedIP.split('.');
      return parseInt(parts[3] || '0', 10);
    })
  );

  usedLastOctets.add(1);

  for (let i = 2; i < 254; i++) {
    if (!usedLastOctets.has(i)) {
      return `${basePrefix}.${i}`;
    }
  }

  return `${basePrefix}.254`;
}

/**
 * Format bytes to readable human strings (e.g. 1.5 MB)
 */
export function formatBytes(bytes: number, decimals: number = 2): string {
  if (bytes === 0) return '0 B';
  const k = 1024;
  const dm = decimals < 0 ? 0 : decimals;
  const sizes = ['B', 'KB', 'MB', 'GB', 'TB'];
  const i = Math.floor(Math.log(bytes) / Math.log(k));
  return parseFloat((bytes / Math.pow(k, i)).toFixed(dm)) + ' ' + sizes[i];
}
